target 'UARoads_swift' do
use_frameworks!

#Constraints
pod 'SnapKit'

#Network
pod 'Alamofire'

#Crashlytics
pod 'Fabric'
pod 'Crashlytics'

#Realm
pod 'RealmSwift'

#Rx stuff
pod 'RxSwift'
pod 'RxCocoa'
#pod 'Moya/RxSwift'
pod 'RxKeyboard'

#JSON
pod 'SwiftyJSON'

#Connection
pod 'UHBConnectivityManager'

#UI elements
pod 'JGProgressHUD'
pod 'UIViewController+ODStatusBar'
pod 'TSValidatedTextField'
pod 'DZNEmptyDataSet'

#extensions
pod 'StfalconSwiftExtensions'

end
